var quotes = [
  '"To live in this world, you must be able to do three things: <br> to love what is mortal, <br> to hold it against your bones knowing your own life depends on it, <br> and when the time comes to let it go, <br> to let it go." <br> - Mary Oliver"',
  '"I exist. In thousands of agonies - I exist. I am tormented on the rack - but i exist! Though I sit alone in a pillar - I exist! I see the son, and if I dont see the sun, I know its there. And theres a whole life in that, in knowing the sun is there" <br> - Fyodor Dostoevsky',
  '"To live content with small means - to seek elegance rather than luxury, and refinement rather than fashion, to be worthy, not respectable, and wealthy, not rich - to study hard, think quietly, talk gently, act frankly, to listen to stars and birds, babes and sages, with open heart - to hear all cheerfully - do all bravely, await occasions - never hurry; <br> in a word, to let the spiritual unbidden and unconscious, grow up through the common. This is to be my symphony" <br> - William Ellery Channing',
  '"The woods are lovely, dark and deep. <br> But I have promises to keep, <br> and miles to go before I sleep <br> and miles to go before I sleep" <br> - Robert Frost',
  '"To Love at all is to be vulnerable." <br> - C.S. Lewis',
  '"Those who control their passions do so because their passions are weak enough to be controlled." <br> - William Blake',
  '"- Why me? <br> - That is a very earthling question to ask, Mr. Pilgrim. Why you? Why us for that matter? Why anything? Because this moment simply is. Have you ever seen bugs trapped in amber? <br> - Yes. <br> - Well, here we are, Mr. Pilgrim, trapped in the amber of this moment. There is no why." <br> Kurt Vonnegut',
  '"But she did look back, and I love her for that, because it was so human. So she was turned to a pillar of salt. So it goes. People arent supposed to look back. I am certainly not going to do it anymore." <br> - Kurt Vonnegut',
  '"- Maybe... youll fall in love with me all over again. <br> - Hell, (I said), I love you enough now. What do you want to do? Ruin me? <br> - Yes, I want to ruin you. <br> - Good, (I said), Thats what I want too." <br> - Ernest Hemmingway',
  '"He was just a coward and that was the worst luck any man could have." <br> - Ernest Hemmingway',
  '"To be able to say: I loved this person, we had a hell of a nice time together, its over but in a way it will never be over and I do know that I for sure loved this person, to be able to say that and mean it, thats rare senor. Thanks rare and valuable." <br> - Ernest Hemmingway',
  '"She was a wild, wicked slip of a girl. She burned too bright for this world." <br> - Emily Bronte',
  '"Some say the world will end in fire, some say in ice. <br> From want Ive tasted of desire I hold with those who favor fire. <br> But if I had to perish twice, I think I know enough of hate to say that for destruction ice is also great and would suffice." <br> - Robert Frost',
  '"And those who were seen dancing were thought to be insane by those who could not hear the music." <br> - Friedrich Nietzche',
  '"From which stars have we fallen to meet each other here." <br> - Robert Frost',
  '"Being against evil doesnt make you good." <br> - Ernest Hemmingway',
  '"Pain and suffering are always inevitable for a large intelligence and a dceep heart." <br> - Fyodor Dostoevesky',
  '"The earth has music for those who listen." <br> - William Shakespeare',
  '"And where 2 raging fires meet together, <br> they do consume the thing that feeds their fury." <br> - William Shakespeare',
  '"The consequence of this is that Im always finding humans at their best and worst. I see their ugly and their beauty. And I wonder how the same thing can be both." <br> - Markus Zusak',
  '"The question is, what color will everything be at the moment when I come for you? What will the sky be saying?" <br> - Markus Zusak',
  '"I have hated the words and I have loved them, and I hope I have made them right." <br> - Markus Zusak',
  '"I think she always nursed a small mad hope." <br> - Vladimir Nabokov',
  '"Sometimes people are beautiful, Not in looks, not in what they say, <br> just in what they are." <br> - Markus Zusak',
  '"To love or have loved that is enough. Ask nothing further. There is no other pearl to be found in the dark folds of life." <br> - Victor Hugo',
  '"The day will be what you make it, <br> so rise, like the sun, <br> and burn!" <br> - William C. Hannan',
  '"A kind of light spread out from her. And everything changed color. And the world opened out. And a day was good to awaken to. And there were no limits to anything. And the people of the world were good and handsome. And I was not afraid any more." <br> - John Steinbeck',
  '"There are darknesses in life and there are lights, <br> and you? <br> You are one of the lights... <br> the light of all lights." <br> - Bram Stoker',
  '"Im so glad I live in a world where there are Octobers." <br> - L.M. Montgomery',
  '"On one side, shame keeps urging: <br> Give her up. <br> Love, on the other side, insists: <br> Do not." <br> - Ovid',
  '"If you wish to glimpse inside a human soul and get to know a man, dont bother analyzing his ways of being silent, of talking, of weeping, of seeing how much he is moved by noble ideas; you will get better results if you just watch him laugh. If he laughs well, hes a good man." <br> - Fyodor Dostoevesky',
  '"We can only know that we know nothing - <br> that is the highest degree of human wisdom." <br> - Leo Tolstoy',
  '"If it is right, it happens - The main thing is not to hurry. Nothing good gets away." <br> - John Steinbeck',
  '"The purpose of life is not to be happy. It is to be useful, to be honerable, to be compassionate, to have it make some difference that you have lived and lived well." <br> - Ralph Waldo Emerson',
  '"Perhaps one did not want to be loved so much as to be understood." <br> - George Orwell',
  '"We shall meet in a place where there is no darkness." <br> - George Orwell',
  '"How beautiful the world was when one looked at it without searching, just looked, simply and innocently." <br> - Hermann Hesse',
  '"It is not for me to judge another mans life. I must judge, I must choose, I must spurn, purely for myself for myself, alone." <br> - Hermann Hesse',
  '"Perhaps... you are seeking all too much? That all your seeking is making you unable to find?" <br> - Hermann Hesse',
  '"Everything is more beautiful because we are doomed. You will never be lovelier than you are now. We will never be here again." <br> - Homer',
  '"I love no one but you, I have discovered, but you are far away and I am here alone. Then this is my life and maybe, however unlikely, Ill find my way back there. Or maybe, one day, Ill settle for second best. And on that same day, hell will freeze over, the sun will burn out, and the stars will fall from the sky." <br> - Lemony Snicket',
  '"But the law of loving other could not be discovered by reason, because it is unreasonable." <br> - Leo Tolstoy',
  '"Seize the moments of happines, love and be loved! That is the only reality in the world, all else is folly. It is the one thing we are interested in here." <br> - Leo Tolstoy',
  ':Why sometimes Ive believed as many as six impossible things before breakfast." <br> - Lewis Carroll',
  '"You are the only person I can talk with about the shade of a cloud, about the song of a thought - and about how, when I went to work today and looked a tall sunflower in the face, it smiled at me with all of its seeds." <br> - Vladimir Nabokov',
  '"You can stroke people with words." <br> - F. Scott Fitzgerald',
  '"Nobody has measured, even the poets, how much a heart can hold." <br> - Zelda Fitzgerald',
  '"I began to realize how important it is to be an enthusiast in life. If you are interested in something, no matter what it is, go at it with full speed. Embrace it with both arms, hug it, love it, and above all become passionate about it. Lukewarm is no good." <br> - Ronald Dahl',
  '"The soul that sees beauty may sometimes walk alone." <br> - Johann Wolfgang von Goethe',
  '"And all I loved, <br> I loved alone." <br> - Edgar Allen Poe',
  '"Some things are more precious because they dont last long." <br> - Oscar Wilde',
  '"I have no notion of loving people by halves, it is not my nature. My attachments are always excessively strong." <br> - Jane Austen',
  '"I wish you to know that you have been the last dream of my soul." <br> - Charles Dickens',
  '"It was not dying that mattered, it was the sadness, the wonder. The few good people crying in the night. The few good people." <br> - Charles Bukowski',
  '"You begin saving the world by saving one person at a time; all else is grandiose romanticism or politics." <br> - Charles Bukowski',
  '"Find what you love and let it kill you." <br> - Charles Bukowski',
  '"I wanted the whole world or nothing." <br> - Charles Bukowski',
  'Understand me. Im not life and ordinary world. I have my madness, I live in another dimension and I do not have time for things that have no soul." <br> - Charles Bukowski',
  '"She had wild eyes, slightly insane. She also carried an overload of compassion that was real enough and which had obviously cost her something." <br> - Charles Bukowski',
  '"I remember awakening one morning and finding everything smeared with the color of forgotten love." <br> - Charles Bukowski',
  '"Alas, said the other, love is its name: love, consoler of humankind, preserver of the universe, soul of all sentient beings, sweet love" <br> "Alas, said candide, I too have known this thing called love, this ruler of hearts, this soul of our soul..." <br> - Voltaire',
  '- "Do you wanna leave soon?" <br> - "No, I want enough time to be in love with everything... and I cry because everything is so beautiful and so short." <br> - Marina Keegan',
  '"But I must admit I miss you quite terribly. <br> The world is too quietly without you nearby." <br> - Lemony Snicket'
]

function newQuote () {
  var randomNumber = Math.floor(Math.random() * (quotes.length))
  document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber]
}
